//THIS FILE SHOULD BE INCLUDED BY USER CODE FOR CONFIGURING THE LIBRARY.
//		USER CODE SHOULD NOT INCLUDE THE INDIVIDUAL .option.h FILES. TYPICALLY
//		THE FILE SHOULD BE INCLUDED IN THE "Crx_stdafx.h" FILE THAT THE USER SHOULD
//		PROVIDE
#include "Crx/OPTION.H/crx/Var.option.h"