//WARNING: NEVER INCLUDE THIS FILE DIRECTLY EXCEPT IN THE CORRESPONDING .c FILE.
//<<START>>	IMPORTANT: FIRST INCLUDE THE CORRESPONDING ".h" FILE
//			INCLUDE ".h" OF C NON CRXed CODE THAT THIS HEADER NEEDS.
//			INCLUDE ".h", NOT ".c.h", OF C CRXed CODE.
#include "Crx/H/crx/c/arrays/StringSmall.h"
//<<END>>

CRX__LIB__C_CODE_BEGIN()

CRX__C__Array__DEFINE(Crx_C_Arrays_StringSmall, crx_c_arrays_stringSmall_, Crx_C_String,
		CRX__C__ARRAYS__STRING_SMALL__PRIVATE__SIZE08_T, CRX__C__ARRAYS__STRING_SMALL__PRIVATE__SIZE08_MAX, 0, 
		CRXM__FALSE, crx_c_string_destruct, crx_c_string_copyConstruct, 
		CRXM__FALSE, CRXM__FALSE)
		
#undef CRX__C__ARRAYS__STRING_SMALL__PRIVATE__SIZE08_T
#undef CRX__C__ARRAYS__STRING_SMALL__PRIVATE__SIZE08_MAX


CRX__LIB__C_CODE_END()