#include <boost/version.hpp>
#include "Crx/H/crx/crx.h"

#define CRX__VAR__OPTION__INT_MODE__32BIT 1
#define CRX__VAR__OPTION__INT_MODE__64BIT 2
#define CRX__VAR__OPTION__INT_MODE__EMULATED 3

#define CRX__VAR__OPTION__HASH_TABLE_IMPLEMENTATION__UNORDERED_MAP 0
#define CRX__VAR__OPTION__HASH_TABLE_IMPLEMENTATION__KHASH 1
#define CRX__VAR__OPTION__HASH_TABLE_IMPLEMENTATION__SORTED_KHASH 2

#define CRX__VAR__OPTION__ARRAY_IMPLEMENTATION__DEQUE 0
#define CRX__VAR__OPTION__ARRAY_IMPLEMENTATION__VARRING 1
#define CRX__VAR__OPTION__ARRAY_IMPLEMENTATION__VARRING_POINTER 2

#define CRX__VAR__OPTION__ERROR_MODE__SWALLOW 0
#define CRX__VAR__OPTION__ERROR_MODE__EXCEPTION 1
#define CRX__VAR__OPTION__ERROR_MODE__PROPOGATER 2
#if(defined(BOOST_VERSION) && (BOOST_VERSION >= 106200) && !defined(BOOST_NO_CXX11_THREAD_LOCAL) && (!defined(BOOST_OS_WINDOWS) || (_WIN32_WINNT >= 0x0600)) && !defined(BOOST_OS_IOS))
	#define CRX__VAR__ERROR_MODE__ERROR_CODE 3
#endif